@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 22 18:55:06 -0600 2019
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim testbench_func_impl -key {Post-Implementation:sim_1:Functional:testbench} -tclbatch testbench.tcl -protoinst "protoinst_files/system_control.protoinst" -log simulate.log"
call xsim  testbench_func_impl -key {Post-Implementation:sim_1:Functional:testbench} -tclbatch testbench.tcl -protoinst "protoinst_files/system_control.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
