# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Brock/School/ECE498/Final Project/linear_layer.srcs/sources_1/bd/system_control/ip/system_control_auto_pc_0/system_control_auto_pc_0.xci
# IP: The module: 'system_control_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Brock/School/ECE498/Final Project/linear_layer.srcs/sources_1/bd/system_control/ip/system_control_auto_pc_0/system_control_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_control_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Brock/School/ECE498/Final Project/linear_layer.srcs/sources_1/bd/system_control/ip/system_control_auto_pc_0/system_control_auto_pc_0.xci
# IP: The module: 'system_control_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Brock/School/ECE498/Final Project/linear_layer.srcs/sources_1/bd/system_control/ip/system_control_auto_pc_0/system_control_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_control_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
