# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_control/system_control.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control || ORIG_REF_NAME==system_control} -quiet] -quiet

# IP: bd/system_control/ip/system_control_processing_system7_0_0/system_control_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_processing_system7_0_0 || ORIG_REF_NAME==system_control_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_axi_dma_0_0/system_control_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_axi_dma_0_0 || ORIG_REF_NAME==system_control_axi_dma_0_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_INTERFACE_AND_MULTIP_0_0/system_control_INTERFACE_AND_MULTIP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_INTERFACE_AND_MULTIP_0_0 || ORIG_REF_NAME==system_control_INTERFACE_AND_MULTIP_0_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_ps7_0_axi_periph_0/system_control_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_control_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_rst_ps7_0_100M_0/system_control_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_control_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_axi_mem_intercon_0/system_control_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_axi_mem_intercon_0 || ORIG_REF_NAME==system_control_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_xbar_0/system_control_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_xbar_0 || ORIG_REF_NAME==system_control_xbar_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_auto_pc_0/system_control_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_auto_pc_0 || ORIG_REF_NAME==system_control_auto_pc_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_auto_us_0/system_control_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_auto_us_0 || ORIG_REF_NAME==system_control_auto_us_0} -quiet] -quiet

# IP: bd/system_control/ip/system_control_auto_us_1/system_control_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_auto_us_1 || ORIG_REF_NAME==system_control_auto_us_1} -quiet] -quiet

# IP: bd/system_control/ip/system_control_auto_pc_1/system_control_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_control_auto_pc_1 || ORIG_REF_NAME==system_control_auto_pc_1} -quiet] -quiet

# XDC: bd/system_control/system_control_ooc.xdc
